import dotenv from "dotenv";
dotenv.config();
export const PORT = process.env.PORT;
export const URL_DB = process.env.URL_DB;
export const SECRET_KEY = process.env.SECRET_KEY;
export const SESSION_KEY = process.env.SESSION_KEY;
export const API_SECRET = process.env.API_SECRET;
export const API_KEY = process.env.API_KEY;
export const CLOUD_NAME = process.env.CLOUD_NAME;
export const IS_PRODUCTION = process.env.NODE_ENV;
